# Generated by Django 2.2.2 on 2019-06-16 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('data_de_cr', models.CharField(max_length=20)),
                ('keyword', models.CharField(max_length=20)),
                ('avaliacao', models.CharField(choices=[('Otimo', 'Otimo'), ('bom', 'Bom'), ('ruim', 'Ruim')], max_length=20)),
                ('likes', models.CharField(max_length=20)),
                ('comentario', models.CharField(max_length=20)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summary.User')),
                ('categoria', models.ManyToManyField(to='summary.Categoria')),
            ],
        ),
    ]
